version: "2"

services:
  mongodb:
    image: mongo
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: cdp
  api:
    build: "."
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      PORT: 8080
      MONGO_URL: mongodb
      MONGO_PORT: 27017
      MONGO_USER: root
      MONGO_PASS: example
      HOST_SRV: hub
  hub:
    image: selenium/hub:3.141.59-xenon
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-xenon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
      - mongodb
      - api
    environment:
      HUB_HOST: hub

volumes:
  mongodb_data:
    driver: local
