// Generated by Selenium IDE
const { Builder, By, Key } = require('selenium-webdriver');
const assert = require('assert');

describe('US', function() {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build();
    vars = {}
  });
  afterEach(async function() {
    await driver.quit();
  });
  it('US#01 Register', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css(".teal")).click();
    await driver.findElement(By.css(".input-field:nth-child(1) > label")).click();
    await driver.findElement(By.id("username")).sendKeys("selenium");
    await driver.findElement(By.id("email")).sendKeys("selenium@mail.fr");
    await driver.findElement(By.id("password")).sendKeys("Passw0rd");
    await driver.findElement(By.id("confirmPassword")).sendKeys("Passw0rd");
    await driver.findElement(By.id("confirmPassword")).sendKeys(Key.ENTER);
    {
      const elements = await driver.findElements(By.css(".toast"));
      assert(elements.length === 1);
    }
  });
  it('US#02 Login', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css(".green")).click();
    await driver.findElement(By.css(".input-field:nth-child(1) > label")).click();
    await driver.findElement(By.id("email")).sendKeys("selenium@mail.fr");
    await driver.findElement(By.id("password")).sendKeys("Passw0rd");
    await driver.findElement(By.css(".green-text")).click();
    {
      const elements = await driver.findElements(By.css(".toast"));
      assert(elements.length === 1);
    }
  });
  it('US#06 First Project', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css(".waves-effect")).click();
    await driver.findElement(By.css(".m8")).click();
    await driver.findElement(By.id("title")).sendKeys("Mon Premier Projet");
    await driver.findElement(By.id("dueDate")).click();
    await driver.findElement(By.css(".datepicker-row:nth-child(5) > td:nth-child(4) > .datepicker-day-button")).click();
    await driver.findElement(By.css(".datepicker-done")).click();
    await driver.findElement(By.id("dueDate")).sendKeys("28/11/2019");
    await driver.findElement(By.id("description")).click();
    await driver.findElement(By.id("description")).sendKeys("Une description !");
    await driver.findElement(By.css(".green-text")).click();
    {
      const elements = await driver.findElements(By.css(".toast"));
      assert(elements.length === 1);
    }
  });
  it('US#06 Next Project', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css(".col > .btn")).click();
    await driver.findElement(By.css(".m8 > label")).click();
    {
      const element = await driver.findElement(By.css(".green-text"));
      await driver.actions({ bridge: true }).moveToElement(element).perform();
    }
    await driver.findElement(By.id("title")).sendKeys("Second Projet");
    await driver.findElement(By.css(".green-text")).click();
    {
      const elements = await driver.findElements(By.css(".toast"));
      assert(elements.length === 1);
    }
  });
  it('US#08 Edit Project', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css("li:nth-child(1) > .collapsible-header")).click();
    await driver.findElement(By.css(".active .row:nth-child(2) > .btn")).click();
    await driver.findElement(By.id("title")).click();
    await driver.findElement(By.id("title")).sendKeys("Mon Premier Projet MAJ");
    await driver.findElement(By.css(".green-text")).click();
  });
  it('US#09 Delete Project', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css("li:nth-child(1) > .collapsible-header")).click();
    await driver.findElement(By.css(".active .row:nth-child(3) > .btn")).click();
    await driver.findElement(By.css(".btn-flat:nth-child(2)")).click();
    {
      const elements = await driver.findElements(By.css(".toast"));
      assert(elements.length === 1);
    }
  });
  it('US#03 Logout', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css(".material-icons:nth-child(2)")).click();
    await driver.findElement(By.linkText("Se Déconnecter")).click();
  })
});
