// Generated by Selenium IDE
const {Builder, By} = require('selenium-webdriver');
const assert = require('assert');

const mongoose = require('mongoose');
const buildConnection = require('../../config/database.config');
const User = mongoose.model('User');
const Project = mongoose.model('Project');

const url = "http://localhost:8080/";

const user = {
  username: 'selenium',
  email: 'selenium@mail.fr',
  password: 'Passw0rd'
};

const firstProject = {
  title: "Mon Premier Projet",
  description: "Une description !",
  dueDate: "31/12/2019"
};

const secondProject = {
  title: "Second Projet"
};

describe('US', function () {
  this.timeout(3000);
  let driver;

  before(async function () {
    driver = await new Builder().forBrowser('chrome').build();
  });

  it('US#01 Register', done => {
    driver.get(url);

    driver
      .findElement(By.css(".teal")).click()
      .then(() => driver.findElement(By.id("username")).sendKeys(user.username))
      .then(() => driver.findElement(By.id("email")).sendKeys(user.email))
      .then(() => driver.findElement(By.id("password")).sendKeys(user.password))
      .then(() => driver.findElement(By.id("confirmPassword")).sendKeys(user.password))
      .then(() => driver.findElement(By.css(".green-text")).click())
      .then(() => driver.findElement(By.css(".toast")))
      .then(toast => toast.getText())
      .then(text => {
        assert(text === "Compte créé avec succès !");
        done();
      });
  });

  it('US#02 Login', done => {
    driver.get(url);

    driver
      .findElement(By.css(".green")).click()
      .then(() => driver.findElement(By.id("email")).sendKeys(user.email))
      .then(() => driver.findElement(By.id("password")).sendKeys(user.password))
      .then(() => driver.findElement(By.css(".green-text")).click())
      .then(() => driver.findElement(By.css(".toast")))
      .then(toast => toast.getText())
      .then(text => {
        assert(text === "Bienvenue " + user.username + " !");
        done();
      });
  });

  it('US#06 First Project', done => {
    driver.get(url);

    driver
      .findElement(By.css(".waves-effect")).click()
      .then(() => driver.findElement(By.id("title")).sendKeys("Mon Premier Projet"))
      .then(() => driver.findElement(By.id("dueDate")).sendKeys("28/11/2019"))
      .then(() => driver.findElement(By.id("description")).sendKeys("Une description !"))
      .then(() => driver.findElement(By.css(".green-text")).click())
      .then(() => driver.findElement(By.css(".toast")))
      .then(toast => toast.getText())
      .then(text => {
        assert(text === "Projet créé avec succès !");
        done();
      });
  });

  /*it('US#06 Next Project', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css(".col > .btn")).click();
    await driver.findElement(By.id("title")).sendKeys("Second Projet");
    await driver.findElement(By.css(".green-text")).click();
    {
      const elements = await driver.findElements(By.css(".toast"));
      assert(elements.length === 1);
    }
  });

  /*it('US#08 Edit Project', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css("li:nth-child(1) > .collapsible-header")).click();
    await driver.findElement(By.css(".active .row:nth-child(2) > .btn")).click();
    await driver.findElement(By.id("title")).click();
    await driver.findElement(By.id("title")).sendKeys("Mon Premier Projet MAJ");
    await driver.findElement(By.css(".green-text")).click();
  });

  it('US#09 Delete Project', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css("li:nth-child(1) > .collapsible-header")).click();
    await driver.findElement(By.css(".active .row:nth-child(3) > .btn")).click();
    await driver.findElement(By.css(".btn-flat:nth-child(2)")).click();
    {
      const elements = await driver.findElements(By.css(".toast"));
      assert(elements.length === 1);
    }
  });

  it('US#03 Logout', async function() {
    await driver.get("http://localhost:8080/");
    await driver.findElement(By.css(".material-icons:nth-child(2)")).click();
    await driver.findElement(By.linkText("Se Déconnecter")).click();
  });*/

  after(done => {
    driver
      .quit()
      .then(() => buildConnection('cdp'))
      .then(() => User.deleteOne({username: user.username}))
      .then(() => Project.deleteOne({title: firstProject.title}))
      .then(() => Project.deleteOne({title: secondProject.title}))
      .then(() => mongoose.disconnect())
      .then(() => done());
  });
});
